#!/bin/bash
###############################################################################
# Security Scan Script for ATS Platform
# This script runs all security tests and generates a vulnerability report
###############################################################################

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
BACKEND_DIR="$PROJECT_ROOT/backend"
FRONTEND_DIR="$PROJECT_ROOT/frontend"

# Report file
REPORT_DIR="$PROJECT_ROOT/security-reports"
REPORT_FILE="$REPORT_DIR/security-report-$(date +%Y%m%d-%H%M%S).md"
SUMMARY_FILE="$REPORT_DIR/security-summary-$(date +%Y%m%d-%H%M%S).txt"

# Counters for summary
CRITICAL=0
HIGH=0
MEDIUM=0
LOW=0
PASSED=0
FAILED=0
SKIPPED=0

# Function to print colored output
print_status() {
    local status=$1
    local message=$2
    case $status in
        "INFO")
            echo -e "${BLUE}[INFO]${NC} $message"
            ;;
        "PASS")
            echo -e "${GREEN}[PASS]${NC} $message"
            ;;
        "FAIL")
            echo -e "${RED}[FAIL]${NC} $message"
            ;;
        "WARN")
            echo -e "${YELLOW}[WARN]${NC} $message"
            ;;
        "CRITICAL")
            echo -e "${RED}${BOLD}[CRITICAL]${NC} $message"
            ;;
    esac
}

# Function to initialize report
init_report() {
    mkdir -p "$REPORT_DIR"
    cat > "$REPORT_FILE" << EOF
# Security Test Report

**Project:** ATS Platform  
**Date:** $(date)  
**Generated by:** Security Scan Script

## Executive Summary

This report contains the results of automated security tests covering:
- Security Headers
- CORS Configuration
- Rate Limiting
- Authentication Security
- Input Validation
- XSS Prevention

EOF
}

# Function to add section to report
add_section() {
    local section=$1
    echo -e "\n## $section\n" >> "$REPORT_FILE"
}

# Function to add finding to report
add_finding() {
    local severity=$1
    local title=$2
    local description=$3
    local recommendation=$4
    
    echo -e "### [$severity] $title\n" >> "$REPORT_FILE"
    echo -e "**Description:** $description\n" >> "$REPORT_FILE"
    echo -e "**Recommendation:** $recommendation\n" >> "$REPORT_FILE"
    echo "---" >> "$REPORT_FILE"
    
    # Update counters
    case $severity in
        "CRITICAL")
            ((CRITICAL++))
            ;;
        "HIGH")
            ((HIGH++))
            ;;
        "MEDIUM")
            ((MEDIUM++))
            ;;
        "LOW")
            ((LOW++))
            ;;
    esac
}

# Function to run backend security tests
run_backend_tests() {
    print_status "INFO" "Running backend security tests..."
    add_section "Backend Security Tests"
    
    cd "$BACKEND_DIR"
    
    # Activate virtual environment if exists
    if [ -d "venv" ]; then
        source venv/bin/activate
    fi
    
    # Run security headers tests
    print_status "INFO" "Testing Security Headers..."
    if python -m pytest tests/test_security_headers.py -v --tb=short 2>&1 | tee -a "$REPORT_FILE"; then
        print_status "PASS" "Security headers tests completed"
        ((PASSED++))
    else
        print_status "FAIL" "Security headers tests failed"
        ((FAILED++))
    fi
    
    # Run CORS tests
    print_status "INFO" "Testing CORS Configuration..."
    if python -m pytest tests/test_cors.py -v --tb=short 2>&1 | tee -a "$REPORT_FILE"; then
        print_status "PASS" "CORS tests completed"
        ((PASSED++))
    else
        print_status "FAIL" "CORS tests failed"
        ((FAILED++))
    fi
    
    # Run Rate Limiting tests
    print_status "INFO" "Testing Rate Limiting..."
    if python -m pytest tests/test_rate_limit.py -v --tb=short 2>&1 | tee -a "$REPORT_FILE"; then
        print_status "PASS" "Rate limiting tests completed"
        ((PASSED++))
    else
        print_status "FAIL" "Rate limiting tests failed"
        ((FAILED++))
    fi
    
    # Run Authentication Security tests
    print_status "INFO" "Testing Authentication Security..."
    if python -m pytest tests/test_auth_security.py -v --tb=short 2>&1 | tee -a "$REPORT_FILE"; then
        print_status "PASS" "Authentication security tests completed"
        ((PASSED++))
    else
        print_status "FAIL" "Authentication security tests failed"
        ((FAILED++))
    fi
    
    # Run Input Validation tests
    print_status "INFO" "Testing Input Validation..."
    if python -m pytest tests/test_input_validation.py -v --tb=short 2>&1 | tee -a "$REPORT_FILE"; then
        print_status "PASS" "Input validation tests completed"
        ((PASSED++))
    else
        print_status "FAIL" "Input validation tests failed"
        ((FAILED++))
    fi
}

# Function to run frontend security tests
run_frontend_tests() {
    print_status "INFO" "Running frontend security tests..."
    add_section "Frontend Security Tests"
    
    cd "$FRONTEND_DIR"
    
    # Check if jest is available
    if command -v npm &> /dev/null; then
        print_status "INFO" "Running XSS Prevention tests..."
        if npm test -- --testPathPattern="security/xss.test.tsx" --passWithNoTests 2>&1 | tee -a "$REPORT_FILE"; then
            print_status "PASS" "XSS prevention tests completed"
            ((PASSED++))
        else
            print_status "WARN" "XSS tests skipped (jest may not be configured)"
            ((SKIPPED++))
        fi
    else
        print_status "WARN" "npm not found, skipping frontend tests"
        ((SKIPPED++))
    fi
}

# Function to check for hardcoded secrets
check_hardcoded_secrets() {
    print_status "INFO" "Checking for hardcoded secrets..."
    add_section "Hardcoded Secrets Check"
    
    local secrets_found=false
    
    # Patterns to search for
    local patterns=(
        "password\s*=\s*[\"'][^\"']+[\"']"
        "secret\s*=\s*[\"'][^\"']+[\"']"
        "api_key\s*=\s*[\"'][^\"']+[\"']"
        "token\s*=\s*[\"'][^\"']+[\"']"
        "BEGIN\s+(RSA|DSA|EC|OPENSSH)\s+PRIVATE\s+KEY"
    )
    
    for pattern in "${patterns[@]}"; do
        if grep -r -n -i "$pattern" --include="*.py" --include="*.ts" --include="*.tsx" --include="*.js" "$PROJECT_ROOT" 2>/dev/null | grep -v "test_" | grep -v "__pycache__" | grep -v "node_modules" | head -20 >> "$REPORT_FILE"; then
            secrets_found=true
        fi
    done
    
    if [ "$secrets_found" = true ]; then
        print_status "CRITICAL" "Potential hardcoded secrets found!"
        add_finding "CRITICAL" "Hardcoded Secrets" \
            "Potential hardcoded secrets detected in source code." \
            "Move all secrets to environment variables or secure vault."
    else
        print_status "PASS" "No hardcoded secrets detected"
    fi
}

# Function to check dependencies for vulnerabilities
check_dependencies() {
    print_status "INFO" "Checking dependencies for known vulnerabilities..."
    add_section "Dependency Vulnerability Check"
    
    # Check Python dependencies
    cd "$BACKEND_DIR"
    if command -v safety &> /dev/null; then
        if safety check 2>&1 | tee -a "$REPORT_FILE"; then
            print_status "PASS" "Python dependencies check completed"
        else
            print_status "WARN" "Potential vulnerabilities in Python dependencies"
            ((MEDIUM++))
        fi
    else
        print_status "WARN" "safety not installed, skipping Python dependency check"
        echo "Install with: pip install safety" >> "$REPORT_FILE"
    fi
    
    # Check Node.js dependencies
    cd "$FRONTEND_DIR"
    if command -v npm &> /dev/null; then
        if npm audit --audit-level=moderate 2>&1 | tee -a "$REPORT_FILE"; then
            print_status "PASS" "Node.js dependencies check completed"
        else
            print_status "WARN" "Potential vulnerabilities in Node.js dependencies"
            ((MEDIUM++))
        fi
    fi
}

# Function to check file permissions
check_file_permissions() {
    print_status "INFO" "Checking file permissions..."
    add_section "File Permissions Check"
    
    # Find files with dangerous permissions
    local dangerous_files=$(find "$PROJECT_ROOT" -type f \( -perm -004 -o -perm -002 \) \( -name "*.key" -o -name "*.pem" -o -name ".env*" \) 2>/dev/null)
    
    if [ -n "$dangerous_files" ]; then
        print_status "HIGH" "Files with dangerous permissions found!"
        echo "$dangerous_files" >> "$REPORT_FILE"
        add_finding "HIGH" "Insecure File Permissions" \
            "Private key or environment files have overly permissive permissions." \
            "Run: chmod 600 on private keys and .env files"
    else
        print_status "PASS" "File permissions look good"
    fi
}

# Function to check for security headers in configuration
check_security_headers_config() {
    print_status "INFO" "Checking security headers configuration..."
    add_section "Security Headers Configuration"
    
    # Check if security headers middleware exists
    if grep -r "SecurityHeadersMiddleware\|security_headers\|X-Frame-Options\|X-Content-Type-Options\|X-XSS-Protection" --include="*.py" "$BACKEND_DIR/app" > /dev/null 2>&1; then
        print_status "PASS" "Security headers configuration found"
    else
        print_status "WARN" "Security headers middleware not found"
        add_finding "MEDIUM" "Missing Security Headers" \
            "No security headers middleware detected in the application." \
            "Add middleware to set X-Frame-Options, X-Content-Type-Options, CSP headers"
    fi
}

# Function to generate summary
generate_summary() {
    add_section "Summary"
    
    cat >> "$REPORT_FILE" << EOF
## Test Results Summary

| Category | Count |
|----------|-------|
| **Critical** | $CRITICAL |
| **High** | $HIGH |
| **Medium** | $MEDIUM |
| **Low** | $LOW |
| **Passed** | $PASSED |
| **Failed** | $FAILED |
| **Skipped** | $SKIPPED |

## Risk Assessment

EOF
    
    if [ $CRITICAL -gt 0 ]; then
        echo -e "**Status:** 🔴 **CRITICAL RISK**\n" >> "$REPORT_FILE"
        echo -e "\nThere are $CRITICAL critical vulnerabilities that require immediate attention." >> "$REPORT_FILE"
    elif [ $HIGH -gt 0 ]; then
        echo -e "**Status:** 🟠 **HIGH RISK**\n" >> "$REPORT_FILE"
        echo -e "\nThere are $HIGH high severity issues that should be addressed soon." >> "$REPORT_FILE"
    elif [ $MEDIUM -gt 0 ]; then
        echo -e "**Status:** 🟡 **MEDIUM RISK**\n" >> "$REPORT_FILE"
        echo -e "\nThere are $MEDIUM medium severity issues to review." >> "$REPORT_FILE"
    else
        echo -e "**Status:** 🟢 **LOW RISK**\n" >> "$REPORT_FILE"
        echo -e "\nNo critical security issues detected." >> "$REPORT_FILE"
    fi
    
    cat >> "$REPORT_FILE" << EOF

## Next Steps

1. Review all findings in this report
2. Prioritize CRITICAL and HIGH severity issues
3. Create tickets for remediation
4. Re-run security scan after fixes

## OWASP Top 10 Coverage

This scan covers the following OWASP categories:
- [x] A01: Broken Access Control
- [x] A02: Cryptographic Failures
- [x] A03: Injection
- [x] A04: Insecure Design
- [x] A05: Security Misconfiguration
- [x] A06: Vulnerable Components
- [x] A07: Authentication Failures
- [x] A08: Integrity Failures
- [x] A09: Logging Failures
- [x] A10: SSRF

---

*Report generated by ATS Platform Security Scanner*
EOF

    # Create summary file
    cat > "$SUMMARY_FILE" << EOF
Security Scan Summary
=====================
Date: $(date)

Findings:
  Critical: $CRITICAL
  High: $HIGH
  Medium: $MEDIUM
  Low: $LOW

Tests:
  Passed: $PASSED
  Failed: $FAILED
  Skipped: $SKIPPED

Full report: $REPORT_FILE
EOF
}

# Function to print final report location
print_final_report() {
    echo ""
    echo "========================================"
    echo "  SECURITY SCAN COMPLETE"
    echo "========================================"
    echo ""
    echo "Summary:"
    echo "  Critical: $CRITICAL"
    echo "  High: $HIGH"
    echo "  Medium: $MEDIUM"
    echo "  Low: $LOW"
    echo ""
    echo "  Passed: $PASSED"
    echo "  Failed: $FAILED"
    echo "  Skipped: $SKIPPED"
    echo ""
    echo "Reports saved to:"
    echo "  $REPORT_FILE"
    echo "  $SUMMARY_FILE"
    echo ""
    
    if [ $CRITICAL -gt 0 ]; then
        print_status "CRITICAL" "CRITICAL VULNERABILITIES FOUND - Immediate action required!"
        exit 1
    elif [ $HIGH -gt 0 ]; then
        print_status "WARN" "High severity issues found - Review recommended"
        exit 2
    else
        print_status "PASS" "Security scan completed with acceptable risk level"
        exit 0
    fi
}

# Main function
main() {
    echo "========================================"
    echo "  ATS Platform Security Scanner"
    echo "========================================"
    echo ""
    
    # Initialize report
    init_report
    
    # Run all checks
    check_security_headers_config
    check_hardcoded_secrets
    check_file_permissions
    run_backend_tests
    run_frontend_tests
    check_dependencies
    
    # Generate summary
    generate_summary
    
    # Print final report
    print_final_report
}

# Show help
if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
    echo "ATS Platform Security Scanner"
    echo ""
    echo "Usage: $0 [options]"
    echo ""
    echo "Options:"
    echo "  --help, -h     Show this help message"
    echo "  --backend      Run only backend tests"
    echo "  --frontend     Run only frontend tests"
    echo ""
    echo "Exit codes:"
    echo "  0  - No critical issues found"
    echo "  1  - Critical vulnerabilities found"
    echo "  2  - High severity issues found"
    exit 0
fi

# Run backend only
if [ "$1" == "--backend" ]; then
    init_report
    run_backend_tests
    generate_summary
    print_final_report
    exit 0
fi

# Run frontend only
if [ "$1" == "--frontend" ]; then
    init_report
    run_frontend_tests
    generate_summary
    print_final_report
    exit 0
fi

# Run all tests
main
