"""Initial migration

Revision ID: 03a8d61a6316
Revises: 
Create Date: 2026-02-11 00:12:09.565838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03a8d61a6316'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'CONSULTANT', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PENDING', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_encrypted', sa.Text(), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_json', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'key', name='uix_config_category_key')
    )
    op.create_index(op.f('ix_configurations_category'), 'configurations', ['category'], unique=False)
    op.create_index(op.f('ix_configurations_key'), 'configurations', ['key'], unique=False)
    op.create_table('job_openings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('seniority', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('assigned_consultant_id', sa.UUID(), nullable=True),
    sa.Column('zoho_job_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_consultant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email_normalized', sa.String(length=255), nullable=True),
    sa.Column('phone_normalized', sa.String(length=50), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('extracted_skills', sa.JSON(), nullable=True),
    sa.Column('extracted_experience', sa.JSON(), nullable=True),
    sa.Column('extracted_education', sa.JSON(), nullable=True),
    sa.Column('job_opening_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_REVIEW', 'SHORTLISTED', 'INTERVIEW', 'DISCARDED', 'HIRED', name='candidatestatus'), nullable=True),
    sa.Column('zoho_candidate_id', sa.String(length=100), nullable=True),
    sa.Column('duplicate_of_id', sa.UUID(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_opening_id'], ['job_openings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=False)
    op.create_index(op.f('ix_candidates_email_normalized'), 'candidates', ['email_normalized'], unique=False)
    op.create_index(op.f('ix_candidates_phone'), 'candidates', ['phone'], unique=False)
    op.create_index(op.f('ix_candidates_phone_normalized'), 'candidates', ['phone_normalized'], unique=False)
    op.create_table('candidate_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('consultant_id', sa.UUID(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('synced_to_zoho', sa.Boolean(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('zoho_sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['consultant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('WHATSAPP', 'EMAIL', name='communicationtype'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'READ', 'FAILED', name='communicationstatus'), nullable=True),
    sa.Column('template_name', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('gaps', sa.JSON(), nullable=True),
    sa.Column('red_flags', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('llm_provider', sa.String(length=50), nullable=True),
    sa.Column('llm_model', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('hard_filters_passed', sa.Boolean(), nullable=True),
    sa.Column('hard_filters_failed', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('evaluation_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluations')
    op.drop_table('communications')
    op.drop_table('candidate_decisions')
    op.drop_index(op.f('ix_candidates_phone_normalized'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_phone'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email_normalized'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_table('job_openings')
    op.drop_index(op.f('ix_configurations_key'), table_name='configurations')
    op.drop_index(op.f('ix_configurations_category'), table_name='configurations')
    op.drop_table('configurations')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
