"""Message templates module migration.

Revision ID: 20260216_002
Revises: 20260216_001
Create Date: 2025-02-16 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20260216_002'
down_revision = '20260216_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create message_templates table
    op.create_table(
        'message_templates',
        sa.Column('template_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('channel', sa.Enum('EMAIL', 'WHATSAPP', 'SMS', name='messagechannel'), nullable=False),
        sa.Column('subject', sa.String(length=255), nullable=True),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_default', sa.Boolean(), nullable=True),
        sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('template_id'),
        sa.UniqueConstraint('name', 'channel', name='uix_template_name_channel')
    )
    
    # Create indexes
    op.create_index(op.f('ix_message_templates_channel'), 'message_templates', ['channel'], unique=False)
    op.create_index(op.f('ix_message_templates_is_active'), 'message_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_message_templates_name'), 'message_templates', ['name'], unique=False)
    
    # Create template_variables table
    op.create_table(
        'template_variables',
        sa.Column('variable_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=False),
        sa.Column('example_value', sa.String(length=255), nullable=True),
        sa.Column('category', sa.String(length=50), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('variable_id'),
        sa.UniqueConstraint('name', name='uix_template_variable_name')
    )
    
    # Create indexes for template_variables
    op.create_index(op.f('ix_template_variables_name'), 'template_variables', ['name'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index(op.f('ix_template_variables_name'), table_name='template_variables')
    op.drop_index(op.f('ix_message_templates_name'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_is_active'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_channel'), table_name='message_templates')
    
    # Drop tables
    op.drop_table('template_variables')
    op.drop_table('message_templates')
    
    # Drop enum
    op.execute("DROP TYPE IF EXISTS messagechannel")
    
    # ### end Alembic commands ###
