"""Core ATS migration - Add Odoo fields and indexes

Revision ID: 002_core_ats
Revises: 03a8d61a6316
Create Date: 2026-02-11 14:15:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '002_core_ats'
down_revision = '03a8d61a6316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted for Core ATS ### #
    
    # 1. Agregar campos Odoo a job_openings
    op.add_column('job_openings', 
        sa.Column('odoo_job_id', sa.String(length=100), nullable=True)
    )
    
    # 2. Agregar campos Odoo a candidates
    op.add_column('candidates',
        sa.Column('odoo_applicant_id', sa.String(length=100), nullable=True)
    )
    
    # 3. Cambiar tipo de score a DECIMAL(5,2) para precisión
    op.alter_column('evaluations', 'score',
        existing_type=sa.Float(),
        type_=sa.DECIMAL(5, 2),
        existing_nullable=True,
        postgresql_using='score::numeric(5,2)'
    )
    
    # 4. Agregar campo direction a communications
    op.add_column('communications',
        sa.Column('direction', sa.String(length=10), nullable=True)
    )
    
    # 5. Crear índices optimizados para queries frecuentes
    
    # Índices para job_openings
    op.create_index('idx_job_openings_status', 'job_openings', ['status'], unique=False)
    op.create_index('idx_job_openings_assigned', 'job_openings', ['assigned_consultant_id'], unique=False)
    op.create_index('idx_job_openings_zoho', 'job_openings', ['zoho_job_id'], unique=False)
    op.create_index('idx_job_openings_odoo', 'job_openings', ['odoo_job_id'], unique=False)
    
    # Índices para candidates
    op.create_index('idx_candidates_job', 'candidates', ['job_opening_id'], unique=False)
    op.create_index('idx_candidates_status', 'candidates', ['status'], unique=False)
    op.create_index('idx_candidates_source', 'candidates', ['source'], unique=False)
    op.create_index('idx_candidates_duplicate', 'candidates', ['is_duplicate'], unique=False)
    op.create_index('idx_candidates_zoho', 'candidates', ['zoho_candidate_id'], unique=False)
    op.create_index('idx_candidates_odoo', 'candidates', ['odoo_applicant_id'], unique=False)
    
    # Índice compuesto para búsqueda de duplicados
    op.create_index('idx_candidates_duplicate_check', 'candidates', 
        ['email_normalized', 'phone_normalized'], unique=False, 
        postgresql_where=sa.text("email_normalized IS NOT NULL OR phone_normalized IS NOT NULL")
    )
    
    # Índices para evaluations
    op.create_index('idx_evaluations_candidate', 'evaluations', ['candidate_id'], unique=False)
    op.create_index('idx_evaluations_decision', 'evaluations', ['decision'], unique=False)
    op.create_index('idx_evaluations_score', 'evaluations', ['score'], unique=False)
    
    # Índices para communications
    op.create_index('idx_communications_candidate', 'communications', ['candidate_id'], unique=False)
    op.create_index('idx_communications_type', 'communications', ['type'], unique=False)
    op.create_index('idx_communications_status', 'communications', ['status'], unique=False)
    op.create_index('idx_communications_external', 'communications', ['external_message_id'], unique=False)
    
    # Índices para candidate_decisions
    op.create_index('idx_decisions_candidate', 'candidate_decisions', ['candidate_id'], unique=False)
    op.create_index('idx_decisions_consultant', 'candidate_decisions', ['consultant_id'], unique=False)
    op.create_index('idx_decisions_synced', 'candidate_decisions', ['synced_to_zoho'], unique=False)
    
    # 6. Actualizar valores de direction en communications existentes (default outbound)
    op.execute("UPDATE communications SET direction = 'outbound' WHERE direction IS NULL")
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted for Core ATS ### #
    
    # Eliminar índices en orden inverso
    op.drop_index('idx_decisions_synced', table_name='candidate_decisions')
    op.drop_index('idx_decisions_consultant', table_name='candidate_decisions')
    op.drop_index('idx_decisions_candidate', table_name='candidate_decisions')
    
    op.drop_index('idx_communications_external', table_name='communications')
    op.drop_index('idx_communications_status', table_name='communications')
    op.drop_index('idx_communications_type', table_name='communications')
    op.drop_index('idx_communications_candidate', table_name='communications')
    
    op.drop_index('idx_evaluations_score', table_name='evaluations')
    op.drop_index('idx_evaluations_decision', table_name='evaluations')
    op.drop_index('idx_evaluations_candidate', table_name='evaluations')
    
    op.drop_index('idx_candidates_duplicate_check', table_name='candidates')
    op.drop_index('idx_candidates_odoo', table_name='candidates')
    op.drop_index('idx_candidates_zoho', table_name='candidates')
    op.drop_index('idx_candidates_duplicate', table_name='candidates')
    op.drop_index('idx_candidates_source', table_name='candidates')
    op.drop_index('idx_candidates_status', table_name='candidates')
    op.drop_index('idx_candidates_job', table_name='candidates')
    
    op.drop_index('idx_job_openings_odoo', table_name='job_openings')
    op.drop_index('idx_job_openings_zoho', table_name='job_openings')
    op.drop_index('idx_job_openings_assigned', table_name='job_openings')
    op.drop_index('idx_job_openings_status', table_name='job_openings')
    
    # Eliminar columnas
    op.drop_column('communications', 'direction')
    op.drop_column('candidates', 'odoo_applicant_id')
    op.drop_column('job_openings', 'odoo_job_id')
    
    # Revertir tipo de score
    op.alter_column('evaluations', 'score',
        existing_type=sa.DECIMAL(5, 2),
        type_=sa.Float(),
        existing_nullable=True,
        postgresql_using='score::double precision'
    )
    
    # ### end Alembic commands ###
