"""Matching IA y extensiones de Job.

Revision ID: 20260212_001
Revises: 20260211_1415
Create Date: 2026-02-12 13:50:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20260212_001_matching_ia'
down_revision = '20260211_1415_002_core_ats'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Agregar columnas a job_openings
    op.add_column('job_openings', sa.Column('requirements', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('job_openings', sa.Column('salary_range_min', sa.Integer(), nullable=True))
    op.add_column('job_openings', sa.Column('salary_range_max', sa.Integer(), nullable=True))
    op.add_column('job_openings', sa.Column('employment_type', sa.String(length=50), nullable=True))
    op.add_column('job_openings', sa.Column('job_description_file_id', postgresql.UUID(as_uuid=True), nullable=True))
    
    # Foreign key para job_description_file_id
    op.create_foreign_key(
        'fk_job_openings_jd_document',
        'job_openings', 'rhtools_documents',
        ['job_description_file_id'], ['id']
    )
    
    # Índices para job_openings
    op.create_index('ix_job_openings_employment_type', 'job_openings', ['employment_type'])
    
    # Crear tabla match_results
    op.create_table(
        'match_results',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('candidate_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('job_opening_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('score', sa.Float(), nullable=False),
        sa.Column('match_details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('recommendation', sa.String(length=20), nullable=False),
        sa.Column('reasoning', sa.Text(), nullable=True),
        sa.Column('strengths', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('gaps', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('red_flags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('analysis_duration_ms', sa.Integer(), nullable=True),
        sa.Column('llm_provider', sa.String(length=50), nullable=True),
        sa.Column('llm_model', sa.String(length=100), nullable=True),
        sa.Column('prompt_version', sa.String(length=20), nullable=True),
        sa.Column('analyzed_by', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('analyzed_at', sa.DateTime(), nullable=True),
        sa.Column('is_cached', sa.String(length=1), nullable=True),
        sa.Column('cache_expires_at', sa.DateTime(), nullable=True),
        sa.Column('cv_version_hash', sa.String(length=64), nullable=True),
        sa.Column('job_version_hash', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['analyzed_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
        sa.ForeignKeyConstraint(['job_opening_id'], ['job_openings.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Índices para match_results
    op.create_index('ix_match_results_candidate_id', 'match_results', ['candidate_id'])
    op.create_index('ix_match_results_job_opening_id', 'match_results', ['job_opening_id'])
    op.create_index('ix_match_results_score', 'match_results', ['score'])
    op.create_index('ix_match_results_recommendation', 'match_results', ['recommendation'])
    op.create_index(
        'ix_match_results_candidate_job',
        'match_results',
        ['candidate_id', 'job_opening_id']
    )
    
    # Crear tabla matching_audit_logs
    op.create_table(
        'matching_audit_logs',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('candidate_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('job_opening_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('match_result_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('ip_address', sa.String(length=50), nullable=True),
        sa.Column('user_agent', sa.String(length=500), nullable=True),
        sa.Column('request_method', sa.String(length=10), nullable=True),
        sa.Column('request_path', sa.String(length=500), nullable=True),
        sa.Column('success', sa.String(length=1), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('processing_time_ms', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
        sa.ForeignKeyConstraint(['job_opening_id'], ['job_openings.id'], ),
        sa.ForeignKeyConstraint(['match_result_id'], ['match_results.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Índices para matching_audit_logs
    op.create_index('ix_matching_audit_candidate_id', 'matching_audit_logs', ['candidate_id'])
    op.create_index('ix_matching_audit_job_id', 'matching_audit_logs', ['job_opening_id'])
    op.create_index('ix_matching_audit_created_at', 'matching_audit_logs', ['created_at'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Eliminar tabla matching_audit_logs
    op.drop_index('ix_matching_audit_created_at', table_name='matching_audit_logs')
    op.drop_index('ix_matching_audit_job_id', table_name='matching_audit_logs')
    op.drop_index('ix_matching_audit_candidate_id', table_name='matching_audit_logs')
    op.drop_table('matching_audit_logs')
    
    # Eliminar tabla match_results
    op.drop_index('ix_match_results_candidate_job', table_name='match_results')
    op.drop_index('ix_match_results_recommendation', table_name='match_results')
    op.drop_index('ix_match_results_score', table_name='match_results')
    op.drop_index('ix_match_results_job_opening_id', table_name='match_results')
    op.drop_index('ix_match_results_candidate_id', table_name='match_results')
    op.drop_table('match_results')
    
    # Eliminar columnas de job_openings
    op.drop_constraint('fk_job_openings_jd_document', 'job_openings', type_='foreignkey')
    op.drop_index('ix_job_openings_employment_type', table_name='job_openings')
    op.drop_column('job_openings', 'job_description_file_id')
    op.drop_column('job_openings', 'employment_type')
    op.drop_column('job_openings', 'salary_range_max')
    op.drop_column('job_openings', 'salary_range_min')
    op.drop_column('job_openings', 'requirements')
    
    # ### end Alembic commands ###
